/**
* 디비 명령문 따로 저장해서 필요할때 사용하기 쉽게 해놓음

*/

drop table if exists member CASCADE;
    create table member(
         id   bigint generated by default as identity,
         name varchar(255),
         primary key (id)
);